spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currencies_test_db
    username: postgres
    password: 1303
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  #      ddl-auto: create
